---
- hosts: all  # noqa: name[play]
  connection: winrm
  vars: 
    ansible_winrm_transport: basic
    ansible_winrm_server_cert_validation: ignore
    ansible_port: 5985
    
  roles:
    - role: "{{ playbook_dir }}"
